package com.gnoblarmod.gnoblars.entity;

import com.gnoblarmod.gnoblars.Gnoblars;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.RandomSource;

/**
 * Looks that tell gnoblars apart in a crowd. Each has its own skin colour, its own outfit colours and either a wart in
 * its own place or none. The textures are generated by tools/paint_texture.py, which holds the same table of colours:
 * keep the names here and there in step.
 */
public enum GnoblarVariant {
    GREEN("green", WartSpot.NONE, 4),
    MOSSY("mossy", WartSpot.NOSE_TOP, 2),
    RUSTY("rusty", WartSpot.CHEEK, 2),
    BARK("bark", WartSpot.FOREHEAD, 2),
    PICKLE("pickle", WartSpot.NOSE_SIDE, 2),
    SOOTY("sooty", WartSpot.NONE, 1);

    /** Where the wart cube sits on the model. */
    public enum WartSpot { NONE, NOSE_TOP, NOSE_SIDE, CHEEK, FOREHEAD }

    private static final GnoblarVariant[] ALL = values();
    private static final int TOTAL_WEIGHT;

    static {
        int total = 0;
        for (GnoblarVariant variant : ALL) {
            total += variant.weight;
        }
        TOTAL_WEIGHT = total;
    }

    private final String id;
    private final WartSpot wart;
    private final int weight;
    private final ResourceLocation texture;

    GnoblarVariant(String id, WartSpot wart, int weight) {
        this.id = id;
        this.wart = wart;
        this.weight = weight;
        this.texture = new ResourceLocation(Gnoblars.MODID, "textures/entity/gnoblar_" + id + ".png");
    }

    public String id() {
        return id;
    }

    public WartSpot wart() {
        return wart;
    }

    public ResourceLocation texture() {
        return texture;
    }

    public static GnoblarVariant byId(int ordinal) {
        return ordinal >= 0 && ordinal < ALL.length ? ALL[ordinal] : GREEN;
    }

    public static GnoblarVariant byName(String name) {
        for (GnoblarVariant variant : ALL) {
            if (variant.id.equals(name)) {
                return variant;
            }
        }
        return GREEN;
    }

    /** A random variant, the plain green one about twice as often as each of the others. */
    public static GnoblarVariant roll(RandomSource random) {
        int pick = random.nextInt(TOTAL_WEIGHT);
        for (GnoblarVariant variant : ALL) {
            pick -= variant.weight;
            if (pick < 0) {
                return variant;
            }
        }
        return GREEN;
    }
}
